from __future__ import annotations

import argparse
import csv

import numpy as np
import torch

from common.data import load_yaml, repo_path
from common.logging_utils import save_json
from common.metrics import safe_corr
from task3_grpo.analyze_group_size import (
    CACHE_GROUP_SIZE,
    _relative_advantages,
    _rewards_for_prompt,
    _tokens_for_prompt,
    load_k8_cache,
)
from task3_grpo.continue_train import fork_name, run_fork

# ---------------------------------------------------------------------------
# Length-normalization study (Step 3). Two parts:
#
#  (A) Matched short continuations from the IDENTICAL midpoint, switching only the sequence
#      normalization: canonical GRPO (divide each response's token sum by its realized length
#      T_k) vs Dr. GRPO (divide by the constant max_completion_length). Everything else -- reward,
#      beta, epsilon, prompts, generation settings, token budget, seed -- is held fixed. Held-out
#      reward/KL/response length come from running task3_grpo.evaluate on each fork adapter; the
#      join lives in scripts.aggregate_task3. THIS is the measurement of the actual runs.
#
#  (B) An ANALYTIC ILLUSTRATION (length_conditioned_diagnostic), NOT a measurement of the forks.
#      It scores ONE fixed completion set (the supplied K-cache) under BOTH normalization formulas.
#      The K-cache was generated by a DIFFERENT policy snapshot than norm_grpo/norm_dr_grpo, so this
#      shows what the two normalizers would do to a fixed completion-length distribution -- it is NOT
#      gradient data recorded from the actual runs. Because the completions are identical across the
#      two formulas, the contrast isolates the normalization alone.
#
# Advantage source (part B): computed LOCALLY via analyze_group_size._relative_advantages, a
# reconstruction of the manual A_k = (r_k - mu_r)/(sigma_r + eps) (population std, additive
# eps=advantage_eps). Deliberately NOT task3_grpo.grpo.group_relative_advantages, whose clamp-based
# normalization (grpo.py:22) is the suspected planted-defect site and is not independently validated.
#
# Gradient model (exact at ratio rho=1, which our 1-epoch updates use up to LoRA dropout):
#   at rho=1, within the clip region, d L / d logpi_t = -(1/N)(1/denom_k) A_k for every response
#   token t of response k. So the gradient GRPO places on response k is, per TOKEN |A_k|/denom_k,
#   and per SEQUENCE |A_k|*T_k/denom_k, with denom_k = T_k (canonical) or L_max (Dr. GRPO). Hence:
#     canonical per-token |A_k|/T_k (long down-weighted), per-seq |A_k| (length-independent);
#     dr_grpo   per-token |A_k|/L_max (length-independent), per-seq |A_k|*T_k/L_max (favors long).
#   L_max only rescales magnitudes: it CANCELS in every correlation and long/short ratio below.
# ---------------------------------------------------------------------------

NORM_TYPES = ("grpo", "dr_grpo")


# ----------------------------- part A: forks --------------------------------
def run_normalization_forks(config_path: str, resume: bool = False, force: bool = False):
    """Matched short continuations from the identical midpoint: canonical GRPO vs Dr. GRPO.
    Each runs once (run_fork skips if its summary already exists unless --force)."""
    summaries = {}
    for loss_type in NORM_TYPES:
        name = fork_name(loss_type)
        cfg = load_yaml(config_path)
        print(f"=== normalization fork {name} (loss_type={loss_type}, {cfg['fork_updates']} updates) ===")
        summaries[name] = run_fork(config_path, loss_type, resume=resume, force=force)
    return summaries


# ----------------------- part B: analytic illustration ----------------------
def _build_completion_table(by_prompt, k, tol, eps):
    """For a fixed completion set, group each prompt's cache into size-k groups, compute
    within-group advantages (local reconstruction), and pair each completion with (|advantage|,
    length=completion_tokens). DEGENERATE groups (within-group reward std <= tol) are EXCLUDED: they
    carry exactly zero advantage -> zero gradient under both normalizers, so they contribute only
    zeros that would bias magnitude means and pollute length correlations. Returns parallel arrays
    (abs_adv, lengths, clipped) plus exclusion counts."""
    abs_adv, lengths, clipped = [], [], []
    n_groups = n_degenerate = 0
    for pid, rows in by_prompt.items():
        rewards = _rewards_for_prompt(rows)
        lens = _tokens_for_prompt(rows)
        clip_flags = [bool(r["clipped_at_max"]) for r in rows[:CACHE_GROUP_SIZE]]
        for start in range(0, CACHE_GROUP_SIZE, k):
            n_groups += 1
            r = torch.tensor(rewards[start : start + k], dtype=torch.float32)
            if float(r.std(unbiased=False)) <= tol:
                n_degenerate += 1
                continue
            adv = _relative_advantages(r, eps)
            for i in range(k):
                abs_adv.append(abs(float(adv[i])))
                lengths.append(lens[start + i])
                clipped.append(clip_flags[start + i])
    counts = {
        "n_groups_total": n_groups,
        "n_degenerate_groups_excluded": n_degenerate,
        "n_completions_total": sum(len(_rewards_for_prompt(rows)) for rows in by_prompt.values()),
        "n_completions_used": len(abs_adv),
        "n_clipped_completions_used": int(sum(clipped)),
    }
    return np.array(abs_adv, dtype=float), np.array(lengths, dtype=float), counts


def _tercile_ratio(values, lengths):
    """mean(values | longest third) / mean(values | shortest third)."""
    if len(values) < 3:
        return float("nan"), float("nan"), float("nan")
    lo, hi = np.percentile(lengths, [100.0 / 3.0, 200.0 / 3.0])
    short = values[lengths <= lo]
    long = values[lengths > hi]
    short_mean = float(np.mean(short)) if len(short) else float("nan")
    long_mean = float(np.mean(long)) if len(long) else float("nan")
    ratio = (long_mean / short_mean) if (np.isfinite(short_mean) and short_mean != 0.0) else float("nan")
    return short_mean, long_mean, ratio


def _grad_stats(abs_adv, lengths, denom):
    """Per-token and per-sequence gradient magnitudes under denom_k, plus their length-conditioning
    (correlation with length and long/short tercile ratio). denom may be an array (T_k) or scalar."""
    safe_len = np.clip(lengths, 1.0, None)
    per_token = abs_adv / denom           # |A_k| / denom_k, per response token
    per_seq = abs_adv * safe_len / denom  # summed over the response's T_k tokens
    pt_short, pt_long, pt_ratio = _tercile_ratio(per_token, lengths)
    ps_short, ps_long, ps_ratio = _tercile_ratio(per_seq, lengths)
    return {
        "mean_per_token_grad": float(np.mean(per_token)),
        "mean_per_sequence_grad": float(np.mean(per_seq)),
        "corr_length_vs_per_token_grad": safe_corr(lengths, per_token),
        "corr_length_vs_per_sequence_grad": safe_corr(lengths, per_seq),
        "per_token_grad_short_tercile_mean": pt_short,
        "per_token_grad_long_tercile_mean": pt_long,
        "per_token_grad_long_over_short": pt_ratio,
        "per_sequence_grad_short_tercile_mean": ps_short,
        "per_sequence_grad_long_tercile_mean": ps_long,
        "per_sequence_grad_long_over_short": ps_ratio,
    }


def length_conditioned_diagnostic(config_path: str):
    cfg = load_yaml(config_path)
    tol = float(cfg.get("group_std_tolerance", cfg.get("advantage_eps", 1e-6)))
    eps = float(cfg.get("advantage_eps", 1e-6))
    k = int(cfg["num_generations"])  # the training group size (baseline K=4)
    # Dr. GRPO normalizer. The cache was generated at cache_generation_cap, so use that here as the
    # constant denominator to match the completion-length distribution being illustrated. It cancels
    # in every correlation/ratio statistic (only rescales absolute magnitudes), so the choice does
    # not affect the length-conditioning evidence. Training dr_grpo uses max_completion_length on its
    # own (512-capped) rollouts; this is an analytic illustration, not a replay of training.
    l_max = float(cfg.get("cache_generation_cap", cfg["max_completion_length"]))
    if CACHE_GROUP_SIZE % k != 0:
        raise ValueError(f"num_generations={k} must divide cache group size {CACHE_GROUP_SIZE}")

    by_prompt = load_k8_cache(cfg["group_cache"])
    abs_adv, lengths, counts = _build_completion_table(by_prompt, k, tol, eps)

    per_norm = {
        "grpo": _grad_stats(abs_adv, lengths, denom=np.clip(lengths, 1.0, None)),  # canonical: denom=T_k
        "dr_grpo": _grad_stats(abs_adv, lengths, denom=l_max),                      # Dr. GRPO: denom=L_max
    }

    result = {
        "config": config_path,
        "analytic_illustration": True,
        "caveat": (
            "ANALYTIC ILLUSTRATION, not a measurement of the norm_grpo/norm_dr_grpo runs. The fixed "
            "K-cache was generated by a different policy snapshot; this shows what the two "
            "normalizers do to a fixed completion-length distribution, not gradient data from the "
            "actual forks (those give held-out reward/KL/length via task3_grpo.evaluate)."
        ),
        "fixed_completion_source": cfg["group_cache"],
        "advantage_source": "local reconstruction (r-mu)/(sigma+eps), additive eps, NOT grpo.py",
        "group_size_k": k,
        "advantage_eps": eps,
        "group_std_tolerance": tol,
        "degenerate_groups_excluded": counts["n_degenerate_groups_excluded"],
        "n_groups_total": counts["n_groups_total"],
        "n_completions_total": counts["n_completions_total"],
        "n_completions_used": counts["n_completions_used"],
        "n_clipped_completions_used": counts["n_clipped_completions_used"],
        "clipped_inclusion_note": (
            "clipped_at_max completions ARE included. Step 1 masks max-length completions from the "
            "TRAINING loss; this diagnostic is an analytic illustration of the normalization's "
            "length-weighting across the realized length distribution, and the long/clipped tail is "
            "exactly where the two normalizers differ most, so excluding it would blunt the contrast."
        ),
        "dr_grpo_normalizer_L_max": l_max,
        "L_max_note": "cancels in every correlation and long/short ratio; only rescales absolute means.",
        "length_stats": {
            "mean": float(np.mean(lengths)), "std": float(np.std(lengths)),
            "min": float(np.min(lengths)), "max": float(np.max(lengths)),
            "p33": float(np.percentile(lengths, 100.0 / 3.0)),
            "p67": float(np.percentile(lengths, 200.0 / 3.0)),
        },
        "gradient_model": (
            "first-order (ratio rho=1) GRPO gradient magnitude placed on response k: per token "
            "|A_k|/denom_k, per sequence |A_k|*T_k/denom_k; denom_k=T_k (canonical) or L_max "
            "(Dr. GRPO). Exact at the epoch-0 ratio used by our 1-epoch updates."
        ),
        "per_normalization": per_norm,
        "interpretation_keys": {
            "per_token_grad_long_over_short": "canonical << 1 (long down-weighted); dr_grpo ~ 1",
            "per_sequence_grad_long_over_short": "canonical ~ 1 (length-independent); dr_grpo > 1 (favors long)",
            "corr_length_vs_per_sequence_grad": "canonical ~ 0; dr_grpo > 0",
        },
    }

    results_dir = repo_path(cfg["results_dir"])
    results_dir.mkdir(parents=True, exist_ok=True)
    save_json(results_dir / "norm_diagnostic.json", result)
    _write_diagnostic_csv(results_dir, result)
    return result


def _write_diagnostic_csv(results_dir, result):
    cols = ["mean_per_token_grad", "mean_per_sequence_grad",
            "corr_length_vs_per_token_grad", "corr_length_vs_per_sequence_grad",
            "per_token_grad_long_over_short", "per_sequence_grad_long_over_short"]
    with (results_dir / "task3_norm_diagnostic.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        # Leading comment row so the file can't be mislabelled as fork measurements.
        w.writerow([f"# ANALYTIC ILLUSTRATION on fixed K-cache (n_completions_used="
                    f"{result['n_completions_used']}, {result['degenerate_groups_excluded']} degenerate "
                    f"groups excluded); NOT gradient data from the norm_grpo/norm_dr_grpo runs"])
        w.writerow(["normalization"] + cols)
        for norm in NORM_TYPES:
            m = result["per_normalization"][norm]
            w.writerow([norm] + [f"{m[c]:.6f}" if isinstance(m[c], float) else m[c] for c in cols])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/grpo.yaml")
    ap.add_argument("--forks-only", action="store_true", help="train the two forks, skip the diagnostic")
    ap.add_argument("--diagnostic-only", action="store_true", help="run the analytic diagnostic only (no training)")
    ap.add_argument("--resume", action="store_true")
    ap.add_argument("--force", action="store_true", help="retrain forks even if already done")
    args = ap.parse_args()

    cfg = load_yaml(args.config)
    print(f"Normalization conditions: {list(NORM_TYPES)}  (loss_type grpo vs dr_grpo)")
    print(f"Fork update budget: {cfg['fork_updates']}  from the identical supplied midpoint")

    if not args.diagnostic_only:
        run_normalization_forks(args.config, resume=args.resume, force=args.force)
    if not args.forks_only:
        result = length_conditioned_diagnostic(args.config)
        print(f"\n[ANALYTIC ILLUSTRATION -- fixed K-cache, not the forks] "
              f"n_completions_used={result['n_completions_used']} "
              f"({result['degenerate_groups_excluded']} degenerate groups excluded, "
              f"{result['n_clipped_completions_used']} clipped included):")
        for norm in NORM_TYPES:
            m = result["per_normalization"][norm]
            print(f"  [{norm}] per-token grad long/short={m['per_token_grad_long_over_short']:.3f}  "
                  f"per-seq grad long/short={m['per_sequence_grad_long_over_short']:.3f}  "
                  f"corr(len,per-seq grad)={m['corr_length_vs_per_sequence_grad']:.3f}")
        print("wrote norm_diagnostic.json, task3_norm_diagnostic.csv")


if __name__ == "__main__":
    main()
